//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Dangerous_Addon_Launcher_V2.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elite_Dangerous_Addon_Launcher_V2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add App.
        /// </summary>
        public static string AddApp_ApplicationArgs {
            get {
                return ResourceManager.GetString("AddApp_ApplicationArgs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string AddApp_ApplicationName {
            get {
                return ResourceManager.GetString("AddApp_ApplicationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application Path.
        /// </summary>
        public static string AddApp_ApplicationPath {
            get {
                return ResourceManager.GetString("AddApp_ApplicationPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Autoexit.
        /// </summary>
        public static string AddApp_Autoexit {
            get {
                return ResourceManager.GetString("AddApp_Autoexit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Autorun.
        /// </summary>
        public static string AddApp_Autorun {
            get {
                return ResourceManager.GetString("AddApp_Autorun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse...
        /// </summary>
        public static string AddApp_Browse {
            get {
                return ResourceManager.GetString("AddApp_Browse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddApp_Cancel {
            get {
                return ResourceManager.GetString("AddApp_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable?.
        /// </summary>
        public static string AddApp_Enable {
            get {
                return ResourceManager.GetString("AddApp_Enable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executable Name.
        /// </summary>
        public static string AddApp_ExecutableName {
            get {
                return ResourceManager.GetString("AddApp_ExecutableName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation URL.
        /// </summary>
        public static string AddApp_InstallationURL {
            get {
                return ResourceManager.GetString("AddApp_InstallationURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save...
        /// </summary>
        public static string AddApp_Save {
            get {
                return ResourceManager.GetString("AddApp_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add App.
        /// </summary>
        public static string AddApp_Title {
            get {
                return ResourceManager.GetString("AddApp_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VR.
        /// </summary>
        public static string AddApp_VR {
            get {
                return ResourceManager.GetString("AddApp_VR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebApp URL.
        /// </summary>
        public static string AddApp_WebAppURL {
            get {
                return ResourceManager.GetString("AddApp_WebAppURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Profile.
        /// </summary>
        public static string AddProfile_Title {
            get {
                return ResourceManager.GetString("AddProfile_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EDData Addon Helper.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom Dialog.
        /// </summary>
        public static string CustomDialog_Title {
            get {
                return ResourceManager.GetString("CustomDialog_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App Name.
        /// </summary>
        public static string DataGrid_AppName {
            get {
                return ResourceManager.GetString("DataGrid_AppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DataGrid_Delete {
            get {
                return ResourceManager.GetString("DataGrid_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DataGrid_Edit {
            get {
                return ResourceManager.GetString("DataGrid_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string DataGrid_Enabled {
            get {
                return ResourceManager.GetString("DataGrid_Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string DataGrid_Launch {
            get {
                return ResourceManager.GetString("DataGrid_Launch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto Quit (close launcher when game exits).
        /// </summary>
        public static string EliteLaunch_AutoQuit {
            get {
                return ResourceManager.GetString("EliteLaunch_AutoQuit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto Run (automatically launch the game).
        /// </summary>
        public static string EliteLaunch_AutoRun {
            get {
                return ResourceManager.GetString("EliteLaunch_AutoRun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse Manually....
        /// </summary>
        public static string EliteLaunch_BrowseManually {
            get {
                return ResourceManager.GetString("EliteLaunch_BrowseManually", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Epic Games Launcher.
        /// </summary>
        public static string EliteLaunch_EpicGames {
            get {
                return ResourceManager.GetString("EliteLaunch_EpicGames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How would you like to launch Elite Dangerous?.
        /// </summary>
        public static string EliteLaunch_HowToLaunch {
            get {
                return ResourceManager.GetString("EliteLaunch_HowToLaunch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch Options.
        /// </summary>
        public static string EliteLaunch_LaunchOptions {
            get {
                return ResourceManager.GetString("EliteLaunch_LaunchOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Legendary Launcher.
        /// </summary>
        public static string EliteLaunch_Legendary {
            get {
                return ResourceManager.GetString("EliteLaunch_Legendary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standard Installation (Scan Computer).
        /// </summary>
        public static string EliteLaunch_StandardInstall {
            get {
                return ResourceManager.GetString("EliteLaunch_StandardInstall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Steam Version.
        /// </summary>
        public static string EliteLaunch_SteamVersion {
            get {
                return ResourceManager.GetString("EliteLaunch_SteamVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Elite Dangerous.
        /// </summary>
        public static string EliteLaunch_Title {
            get {
                return ResourceManager.GetString("EliteLaunch_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VR Mode.
        /// </summary>
        public static string EliteLaunch_VRMode {
            get {
                return ResourceManager.GetString("EliteLaunch_VRMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom Error.
        /// </summary>
        public static string ErrorBox_Title {
            get {
                return ResourceManager.GetString("ErrorBox_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Elite Dangerous (Epic) Detected.
        /// </summary>
        public static string LegendarySettings_EpicDetected {
            get {
                return ResourceManager.GetString("LegendarySettings_EpicDetected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global Launch Parameters:.
        /// </summary>
        public static string LegendarySettings_GlobalParams {
            get {
                return ResourceManager.GetString("LegendarySettings_GlobalParams", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Legendary Settings (Epic Version Detected).
        /// </summary>
        public static string LegendarySettings_Title {
            get {
                return ResourceManager.GetString("LegendarySettings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add App.
        /// </summary>
        public static string MainWindow_AddApp {
            get {
                return ResourceManager.GetString("MainWindow_AddApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Profile.
        /// </summary>
        public static string MainWindow_AddProfile {
            get {
                return ResourceManager.GetString("MainWindow_AddProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close apps on Exit.
        /// </summary>
        public static string MainWindow_CloseAppsOnExit {
            get {
                return ResourceManager.GetString("MainWindow_CloseAppsOnExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy Profile.
        /// </summary>
        public static string MainWindow_CopyProfile {
            get {
                return ResourceManager.GetString("MainWindow_CopyProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy to profile....
        /// </summary>
        public static string MainWindow_CopyToProfile {
            get {
                return ResourceManager.GetString("MainWindow_CopyToProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string MainWindow_Default {
            get {
                return ResourceManager.GetString("MainWindow_Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MainWindow_Export {
            get {
                return ResourceManager.GetString("MainWindow_Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string MainWindow_Import {
            get {
                return ResourceManager.GetString("MainWindow_Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string MainWindow_Launch {
            get {
                return ResourceManager.GetString("MainWindow_Launch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string MainWindow_Logs {
            get {
                return ResourceManager.GetString("MainWindow_Logs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        public static string MainWindow_Profile {
            get {
                return ResourceManager.GetString("MainWindow_Profile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profiles...
        /// </summary>
        public static string MainWindow_Profiles {
            get {
                return ResourceManager.GetString("MainWindow_Profiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove Profile.
        /// </summary>
        public static string MainWindow_RemoveProfile {
            get {
                return ResourceManager.GetString("MainWindow_RemoveProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename Profile.
        /// </summary>
        public static string MainWindow_RenameProfile {
            get {
                return ResourceManager.GetString("MainWindow_RenameProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle Theme.
        /// </summary>
        public static string MainWindow_ToggleTheme {
            get {
                return ResourceManager.GetString("MainWindow_ToggleTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application name is required..
        /// </summary>
        public static string Message_AppNameRequired {
            get {
                return ResourceManager.GetString("Message_AppNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this profile?.
        /// </summary>
        public static string Message_ConfirmRemoveProfile {
            get {
                return ResourceManager.GetString("Message_ConfirmRemoveProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Elite Dangerous was not found on your computer..
        /// </summary>
        public static string Message_EliteDangerousNotFound {
            get {
                return ResourceManager.GetString("Message_EliteDangerousNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profiles exported successfully..
        /// </summary>
        public static string Message_ExportSuccess {
            get {
                return ResourceManager.GetString("Message_ExportSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profiles imported successfully..
        /// </summary>
        public static string Message_ImportSuccess {
            get {
                return ResourceManager.GetString("Message_ImportSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application path or WebApp URL is required..
        /// </summary>
        public static string Message_PathOrUrlRequired {
            get {
                return ResourceManager.GetString("Message_PathOrUrlRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A profile with this name already exists..
        /// </summary>
        public static string Message_ProfileAlreadyExists {
            get {
                return ResourceManager.GetString("Message_ProfileAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile name is required..
        /// </summary>
        public static string Message_ProfileNameRequired {
            get {
                return ResourceManager.GetString("Message_ProfileNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Message_Success {
            get {
                return ResourceManager.GetString("Message_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Message_Warning {
            get {
                return ResourceManager.GetString("Message_Warning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename Profile.
        /// </summary>
        public static string RenameProfile_Title {
            get {
                return ResourceManager.GetString("RenameProfile_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching for Elite Dangerous....
        /// </summary>
        public static string SearchProgress_Searching {
            get {
                return ResourceManager.GetString("SearchProgress_Searching", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching for Elite Dangerous.
        /// </summary>
        public static string SearchProgress_Title {
            get {
                return ResourceManager.GetString("SearchProgress_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string WhatsNew_Close {
            get {
                return ResourceManager.GetString("WhatsNew_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to What's New.
        /// </summary>
        public static string WhatsNew_Title {
            get {
                return ResourceManager.GetString("WhatsNew_Title", resourceCulture);
            }
        }
    }
}
